
# PostgreSQL Data
chat-bot-pgsql-data:
  driver: local

# Redis Data
chat-bot-redis-data:
  driver: local

# ~/.config
chat-bot-temp-config:
  driver: local

# ~/.cache
chat-bot-temp-cache:
  driver: local

# ~/.composer
chat-bot-temp-composer:
  driver: local

services:

  mailcatcher:
    image: ambientum/mailcatcher:latest
    container_name: chat-bot-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    
  
  mysql:
    image: ambientum/mysql:5.7
    container_name: chat-bot-mysql
    volumes:
      - chat-bot-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=chatbot
      - MYSQL_DATABASE=chatbot
      - MYSQL_USER=chatbot
      - MYSQL_PASSWORD=chatbot

  cache:
    image: redis:4.0
    container_name: chat-bot-redis
    command: --appendonly yes
    volumes:
      - chat-bot-redis-data:/data
    ports:
      - 6379:6379

  app:
    image: ambientum/php:7.1-nginx
    container_name: chat-bot-api
    environment:
      - XDEBUG_ENABLE=true
      - PHP_IDE_CONFIG=serverName=ambientum
    volumes:
      - .:/var/www/app
      - chat-bot-temp-config:/home/ambientum/.config
      - chat-bot-temp-cahe:/home/ambientum/.cache
      - chat-bot-temp-local:/home/ambientum/.local
      - chat-bot-temp-composer:/home/ambientum/.composer
    ports:
      - 8080:8080
      - 8083:8083
    links:
      - mysql
      - cache
      - mailcatcher

#  queue:
#    image: ambientum/php:7.1
#    container_name: chat-bot-queue
#    command: php artisan horizon
#    volumes:
#      - .:/var/www/app
#      - chat-bot-temp-config:/home/ambientum/.config
#      - chat-bot-temp-cahe:/home/ambientum/.cache
#      - chat-bot-temp-local:/home/ambientum/.local
#      - chat-bot-temp-composer:/home/ambientum/.composer
#    links:
#      - mysql
#      - cache
#      - mailcatcher