####
# ATENTION:
# Replace all occurences of chat-bot with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  chat-bot-postgres-data:
    driver: local

  # MySQL Data
  chat-bot-mysql-data:
    driver: local

  # Redis Data
  chat-bot-redis-data:
    driver: local

services:
  # Postgres (9.6)
  postgres:
    image: ambientum/postgres:9.6
    container_name: chat-bot-postgres
    volumes:
      - chat-bot-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=chat-bot
      - POSTGRES_DB=chat-bot
      - POSTGRES_USER=chat-bot

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: chat-bot-mysql
    volumes:
      - chat-bot-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chatbot
      - MYSQL_DATABASE=chatbot
      - MYSQL_USER=chatbot
      - MYSQL_PASSWORD=chatbot

  # Redis
  cache:
    image: ambientum/redis:4.0
    container_name: chat-bot-redis
    command: --appendonly yes
    volumes:
      - chat-bot-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: chat-bot-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
      - "8083:8083"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: chat-bot-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache